services:

  kb-postgres:
    image: postgres:17.5
    container_name: kb_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kb_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kb-adminer:
    image: adminer
    container_name: kb_adminer
    restart: always
    ports:
      - 8080:8080
  kb-gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: kb_gitlab
    
    restart: always
    ports:
      - "8929:8929"
      - "10022:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['gitlab_default_can_create_group'] = true
        
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab 

volumes:
  postgres_data:
  gitlab_data:
  gitlab_logs:
  gitlab_config:

